import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";
import gadget1 from "../assets/images/products/gadgets/gadget1.png";
import gadget2 from "../assets/images/products/gadgets/gadget2.png";
import gadget3 from "../assets/images/products/gadgets/gadget3.png";
import gadget4 from "../assets/images/products/gadgets/gadget4.png";
import gadget6 from "../assets/images/products/gadgets/gadget6.png";
import gadget7 from "../assets/images/products/gadgets/gadget7.png";
import gadget5 from "../assets/images/products/gadgets/gadget5.png";
import gadget8 from "../assets/images/products/gadgets/gadget8.png";


import clothes1 from "../assets/images/products/clothes/clothes1.png";
import clothes2 from "../assets/images/products/clothes/clothes2.png";
import clothes3 from "../assets/images/products/clothes/clothes3.png";
import clothes4 from "../assets/images/products/clothes/clothes4.png";
import clothes5 from "../assets/images/products/clothes/clothes5.png";
import clothes6 from "../assets/images/products/clothes/clothes6.png";
import clothes7 from "../assets/images/products/clothes/clothes7.png";
import clothes8 from "../assets/images/products/clothes/clothes8.png";
import clothes9 from "../assets/images/products/clothes/clothes9.png";
import clothes10 from "../assets/images/products/clothes/clothes10.png";
import clothes11 from "../assets/images/products/clothes/clothes11.png";
import clothes13 from "../assets/images/products/clothes/clothes13.png";
import clothes12 from "../assets/images/products/clothes/clothes12.png";


import furniture1 from "../assets/images/products/furniture/furniture1.png";
import furniture2 from "../assets/images/products/furniture/furniture2.png";
import furniture3 from "../assets/images/products/furniture/furniture3.png";
import furniture4 from "../assets/images/products/furniture/furniture4.png";


import elec1 from "../assets/images/products/electronics/elec1.png";
import elec2 from "../assets/images/products/electronics/elec2.png";
import elec3 from "../assets/images/products/electronics/elec3.png";
import elec4 from "../assets/images/products/electronics/elec4.png";
import elec5 from "../assets/images/products/electronics/elec5.png";
import elec6 from "../assets/images/products/electronics/elec6.png";
import elec7 from "../assets/images/products/electronics/elec7.png";
import elec8 from "../assets/images/products/electronics/elec8.png";



// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
// export const SplOfferData = [
//   {
//     _id: "201",
//     img: spfOne,
//     productName: "Cap for Boys",
//     price: "35.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: "202",
//     img: newArrFour,
//     productName: "Tea Table",
//     price: "180.00",
//     color: "Gray",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: "203",
//     img: spfThree,
//     productName: "Headphones",
//     price: "25.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: "204",
//     img: spfFour,
//     productName: "Sun glasses",
//     price: "220.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
// ];
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Cap for Boys",
    category: "accessories",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Tea Table",
    category: "others",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    category: "electronics",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Sun glasses",
    category: "electronics",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];

// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

// export const paginationItems = [
//   {
//     _id: 1001,
//     img: spfOne,
//     productName: "Cap for Boys",
//     price: "35.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1002,
//     img: spfTwo,
//     productName: "Tea Table",
//     price: "180.00",
//     color: "Gray",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1003,
//     img: spfThree,
//     productName: "Headphones",
//     price: "25.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1004,
//     img: spfFour,
//     productName: "Sun glasses",
//     price: "220.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1005,
//     img: bestSellerOne,
//     productName: "Flower Base",
//     price: "35.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1006,
//     img: bestSellerTwo,
//     productName: "New Backpack",
//     price: "180.00",
//     color: "Gray",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1007,
//     img: bestSellerThree,
//     productName: "Household materials",
//     price: "25.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1008,
//     img: bestSellerFour,
//     productName: "Travel Bag",
//     price: "220.00",
//     color: "Black",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1009,
//     img: newArrOne,
//     productName: "Round Table Clock",
//     price: "44.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1010,
//     img: newArrTwo,
//     productName: "Smart Watch",
//     price: "250.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1011,
//     img: newArrThree,
//     productName: "cloth Basket",
//     price: "80.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1012,
//     img: newArrFour,
//     productName: "Funny toys for babies",
//     price: "60.00",
//     color: "Mixed",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1013,
//     img: newArrTwo,
//     productName: "Funny toys for babies",
//     price: "60.00",
//     color: "Mixed",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },

//   {
//     _id: 1014,
//     img: newArrTwo,
//     productName: "Smart Watch",
//     price: "250.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1015,
//     img: newArrFour,
//     productName: "Funny toys for babies",
//     price: "60.00",
//     color: "Mixed",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1016,
//     img: newArrTwo,
//     productName: "Smart Watch",
//     price: "250.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1017,
//     img: bestSellerFour,
//     productName: "Travel Bag",
//     price: "220.00",
//     color: "Black",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1018,
//     img: newArrOne,
//     productName: "Round Table Clock",
//     price: "44.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1019,
//     img: newArrTwo,
//     productName: "Smart Watch",
//     price: "250.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1020,
//     img: newArrThree,
//     productName: "cloth Basket",
//     price: "80.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1021,
//     img: spfThree,
//     productName: "Headphones",
//     price: "25.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1022,
//     img: spfFour,
//     productName: "Sun glasses",
//     price: "220.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1023,
//     img: bestSellerOne,
//     productName: "Flower Base",
//     price: "35.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1024,
//     img: spfOne,
//     productName: "Cap for Boys",
//     price: "35.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1025,
//     img: spfTwo,
//     productName: "Tea Table",
//     price: "180.00",
//     color: "Gray",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1026,
//     img: spfThree,
//     productName: "Headphones",
//     price: "25.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1027,
//     img: spfFour,
//     productName: "Sun glasses",
//     price: "220.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1028,
//     img: bestSellerOne,
//     productName: "Flower Base",
//     price: "35.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1029,
//     img: bestSellerTwo,
//     productName: "New Backpack",
//     price: "180.00",
//     color: "Gray",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1030,
//     img: bestSellerThree,
//     productName: "Household materials",
//     price: "25.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1031,
//     img: bestSellerFour,
//     productName: "Travel Bag",
//     price: "220.00",
//     color: "Black",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1032,
//     img: newArrOne,
//     productName: "Round Table Clock",
//     price: "44.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1033,
//     img: newArrTwo,
//     productName: "Smart Watch",
//     price: "250.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1034,
//     img: newArrThree,
//     productName: "cloth Basket",
//     price: "80.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1035,
//     img: newArrFour,
//     productName: "Funny toys for babies",
//     price: "60.00",
//     color: "Mixed",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1036,
//     img: newArrTwo,
//     productName: "Funny toys for babies",
//     price: "60.00",
//     color: "Mixed",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1037,
//     img: newArrFour,
//     productName: "Funny toys for babies",
//     price: "60.00",
//     color: "Mixed",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1038,
//     img: newArrTwo,
//     productName: "Smart Watch",
//     price: "250.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1039,
//     img: bestSellerFour,
//     productName: "Travel Bag",
//     price: "220.00",
//     color: "Black",
//     badge: false,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1040,
//     img: newArrOne,
//     productName: "Round Table Clock",
//     price: "44.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1041,
//     img: newArrTwo,
//     productName: "Smart Watch",
//     price: "250.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1042,
//     img: newArrThree,
//     productName: "cloth Basket",
//     price: "80.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1043,
//     img: spfThree,
//     productName: "Headphones",
//     price: "25.00",
//     color: "Mixed",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1044,
//     img: spfFour,
//     productName: "Sun glasses",
//     price: "220.00",
//     color: "Black",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1045,
//     img: bestSellerOne,
//     productName: "Flower Base",
//     price: "35.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
//   {
//     _id: 1046,
//     img: spfOne,
//     productName: "Cap for Boys",
//     price: "35.00",
//     color: "Blank and White",
//     badge: true,
//     des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
//   },
// ];

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Cap for Boys",
    category: "clothes",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Tea Table",
    category: "furniture",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Headphones",
    category: "gadgets",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Sun glasses",
    category: "accessories",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Flower Base",
    category: "others",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "New Backpack",
    category: "accessories",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Household materials",
    category: "others",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Travel Bag",
    category: "accessories",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Round Table Clock",
    category: "electronics",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Smart Watch",
    category: "gadgets",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },

  /* 🔁 REPEATS — same logic applied */

  {
    _id: 1011,
    img: newArrThree,
    productName: "cloth Basket",
    category: "others",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Funny toys for babies",
    category: "others",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },

  {
    _id: 1046,
    img: spfOne,
    productName: "Cap for Boys",
    category: "accessories",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 1047,
    img: gadget1,
    productName: "Iphone 15",
    category: "gadgets",
    price: "35.00",
    color: " White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    _id: 1048,
    img: gadget2,
    productName: "Apple White AirPods",
    category: "gadgets",
    price: "330.00",
    color: "White",
    badge: true,
    des: "Premium wireless earbuds with high-quality sound and seamless connectivity.",
  },
  {
    _id: 1049,
    img: gadget3,
    productName: "Wireless Joystick",
    category: "gadgets",
    price: "350.00",
    color: "Black",
    badge: false,
    des: "Ergonomic wireless joystick for smooth and responsive gaming experience.",
  },
  {
    _id: 1050,
    img: gadget4,
    productName: "Drone with Camera",
    category: "gadgets",
    price: "600.00",
    color: "Gray",
    badge: true,
    des: "High-performance drone with HD camera for aerial photography.",
  },
  {
    _id: 1051,
    img: gadget5,
    productName: "iPad 9th Gen",
    category: "gadgets",
    price: "870.00",
    color: "Silver",
    badge: false,
    des: "Apple iPad 9th generation with powerful performance and sleek design.",
  },
  {
    _id: 1052,
    img: gadget6,
    productName: "Ultra HD TV",
    category: "gadgets",
    price: "2000.00",
    color: "Black",
    badge: true,
    des: "Ultra HD smart TV with stunning visuals and immersive sound.",
  },
  {
    _id: 1053,
    img: gadget7,
    productName: "Apple Watch 2nd Gen",
    category: "gadgets",
    price: "400.00",
    color: "White",
    badge: false,
    des: "Smart watch with fitness tracking and seamless Apple ecosystem support.",
  },
  {
    _id: 1054,
    img: gadget8,
    productName: "Wireless Headset",
    category: "gadgets",
    price: "500.00",
    color: "white",
    badge: false,
    des: "Comfortable wireless headset with noise isolation and rich sound.",
  },
  {
    _id: 1054,
    img: clothes1,
    productName: "Gradient Graphic T-shirt",
    category: "clothes",
    price: "145.00",
    color: "Multi",
    badge: true,
    des: "Stylish gradient graphic t-shirt made from premium cotton.",
  },
  {
    _id: 1055,
    img: clothes2,
    productName: "Polo with Tipping Details",
    category: "clothes",
    price: "180.00",
    color: "Navy",
    badge: false,
    des: "Classic polo shirt with modern tipping detail.",
  },
  {
    _id: 1056,
    img: clothes3,
    productName: "Black Striped T-shirt",
    category: "clothes",
    price: "120.00",
    color: "Black",
    badge: false,
    des: "Comfortable striped t-shirt for everyday wear.",
  },
  {
    _id: 1057,
    img: clothes4,
    productName: "Skinny Fit Jeans",
    category: "clothes",
    price: "240.00",
    color: "Blue",
    badge: true,
    des: "Slim and stylish skinny-fit denim jeans.",
  },
  {
    _id: 1058,
    img: clothes5,
    productName: "Checkered Shirt",
    category: "clothes",
    price: "260.00",
    color: "Red",
    badge: false,
    des: "Casual checkered shirt with a modern fit.",
  },
  {
    _id: 1059,
    img: clothes6,
    productName: "Sleeve Striped T-shirt",
    category: "clothes",
    price: "130.00",
    color: "Black",
    badge: false,
    des: "Minimal t-shirt with striped sleeve detail.",
  },
  {
    _id: 1060,
    img: clothes7,
    productName: "Vertical Striped Shirt",
    category: "clothes",
    price: "212.00",
    color: "Green",
    badge: false,
    des: "Formal vertical striped shirt with clean tailoring.",
  },
  {
    _id: 1061,
    img: clothes8,
    productName: "Courage Graphic T-shirt",
    category: "clothes",
    price: "145.00",
    color: "Brown",
    badge: true,
    des: "Bold graphic t-shirt with premium print.",
  },
  {
    _id: 1062,
    img: clothes9,
    productName: "Loose Fit Bermuda Shorts",
    category: "clothes",
    price: "80.00",
    color: "Khaki",
    badge: false,
    des: "Relaxed-fit bermuda shorts for casual comfort.",
  },
  {
    _id: 1063,
    img: clothes10,
    productName: "Lifestyle Shoes",
    category: "clothes",
    price: "200.00",
    color: "White",
    badge: false,
    des: "Comfortable lifestyle shoes for daily wear.",
  },
  {
    _id: 1064,
    img: clothes11,
    productName: "Basketball Shoes",
    category: "clothes",
    price: "300.00",
    color: "white",
    badge: true,
    des: "High-performance basketball shoes with superior grip.",
  },
  {
    _id: 1065,
    img: clothes12,
    productName: "ADIDAS 4DFWD X PARLEY Running Shoes",
    category: "clothes",
    price: "380.00",
    color: "orange",
    badge: true,
    des: "Eco-friendly performance running shoes by Adidas.",
  },
  {
    _id: 1066,
    img: clothes13,
    productName: "ADIDAS 4DFWD X PARLEY Running Shoes",
    category: "clothes",
    price: "350.00",
    color: "Green",
    badge: false,
    des: "Lightweight Adidas running shoes with responsive cushioning.",
  },
  {
    _id: 1067,
    img: furniture1,
    productName: "Native Sofa",
    category: "furniture",
    price: "200.00",
    color: "Black",
    badge: false,
    des: "Comfortable native-style sofa with a sturdy wooden frame.",
  },
  {
    _id: 1068,
    img: furniture2,
    productName: "Native Sofa",
    category: "furniture",
    price: "250.00",
    color: "Grey",
    badge: true,
    des: "Modern grey native sofa designed for comfort and elegance.",
  },
  {
    _id: 1069,
    img: furniture3,
    productName: "Woven Chair",
    category: "furniture",
    price: "300.00",
    color: "Brown",
    badge: true,
    des: "Handcrafted woven chair with a natural finish.",
  },
  {
    _id: 1070,
    img: furniture4,
    productName: "Native Light Chair",
    category: "furniture",
    price: "250.00",
    color: "Beige",
    badge: false,
    des: "Lightweight native-style chair perfect for modern interiors.",
  },



  {
  _id: 1071,
  img: elec1,
  productName: "Washing Machine",
  category: "electronics",
  price: "500.00",
  color: "Silver",
  badge: true,
  des: "High-performance washing machine with energy-saving technology.",
},
{
  _id: 1072,
  img: elec2,
  productName: "Electric Hot Plate",
  category: "electronics",
  price: "356.00",
  color: "Black",
  badge: false,
  des: "Compact electric hot plate ideal for quick cooking.",
},
{
  _id: 1073,
  img: elec3,
  productName: "Electric Iron",
  category: "electronics",
  price: "450.00",
  color: "Blue",
  badge: false,
  des: "Powerful steam iron for wrinkle-free clothes.",
},
{
  _id: 1074,
  img: elec4,
  productName: "Refrigerator",
  category: "electronics",
  price: "620.00",
  color: "Silver",
  badge: true,
  des: "Large-capacity refrigerator with fast cooling system.",
},
{
  _id: 1075,
  img: elec5,
  productName: "Power Generator",
  category: "electronics",
  price: "600.00",
  color: "Yellow",
  badge: true,
  des: "Reliable power generator suitable for home and office use.",
},
{
  _id: 1076,
  img: elec6,
  productName: "Air Conditioner",
  category: "electronics",
  price: "750.00",
  color: "White",
  badge: true,
  des: "Energy-efficient air conditioner with rapid cooling.",
},
{
  _id: 1077,
  img: elec7,
  productName: "65-Inch Smart TV",
  category: "electronics",
  price: "800.00",
  color: "Black",
  badge: true,
  des: "Ultra HD 65-inch smart television with vibrant display.",
},
{
  _id: 1078,
  img: elec8,
  productName: "Electric Oven",
  category: "electronics",
  price: "450.00",
  color: "Black",
  badge: false,
  des: "Multi-function electric oven perfect for baking and grilling.",
},

];

// =================== PaginationItems End here =================
